### ISSUE TITLE
Create API documentation automatically

### ISSUE THREAD

**Issue by knutole** [py-stockfish/stockfish#20]
- The codebase is well documented inline with [Google Python Style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods). 
- The project could leverage this to automatically keep an updated documentation using a documentation tool like https://pdoc.dev/docs. 
- This makes API documentation easier to maintain, and it will bring more value to users.
- Docs could be hosted on Github Pages automatically using Github Workflows, and could look something like this:

<img width="1185" alt="Screenshot 2023-04-11 at 12 26 32" src="https://user-images.githubusercontent.com/2197944/231133634-7ac56de9-096d-47f9-b973-1eae165e3c4a.png">
<img width="1188" alt="Screenshot 2023-04-11 at 12 27 06" src="https://user-images.githubusercontent.com/2197944/231133651-f0bfa3e3-3830-41f3-9f62-e2aeee8666d1.png">
<img width="1182" alt="Screenshot 2023-04-11 at 12 27 46" src="https://user-images.githubusercontent.com/2197944/231133659-8aade1f6-d135-407f-8596-fc22fdfd2947.png">

**Comment by knutole** [comment]
I'd be happy to work on this, if this is something that you think it suitable for this repo, @kieferro @johndoknjas.

**Comment by johndoknjas** [comment]
@knutole Sure, I think that would be nice to have :) Thanks!
