### ISSUE TITLE
get_evaluation() misleading name

### ISSUE THREAD

**Issue by RottenSchnitzel** [py-stockfish/stockfish#37]
When calling get_evaluation() I expect the command `eval` to be put into stockfish. Currently the skript just executes a bestmove search and then uses the score of stockfishs best move.

This feature makes sense but is very misleading since it is called "get_evaluation". Maybe name it "get_bestmove_score" and actually call eval for "get_evaluation".

Very quick fix would be to at least add a note in the Readme.

**Comment by johndoknjas** [comment]
@RottenSchnitzel Thanks for pointing this out. Note though that 'eval' doesn't do any search (just directly applies the evaluation function to the current position), so it's not Stockfish's "true" evaluation. But it's good to have this static evaluation as an option, and to make the documentation for get_evaluation() clearer.
