### ISSUE TITLE
Support for stockfish 16?

### ISSUE THREAD

**Issue by arikanev** [py-stockfish/stockfish#53]
Love your guys work. Wondering if you will have support for newest stockfish engine. Thanks.

**Comment by kieferro** [comment]
> Love your guys work

Thanks <3



> Wondering if you will have support for newest stockfish engine

Even though our CI pipeline isn't running on stockfish 16, I did some local tests and had no problems with it. Theoretically, the engine itself should also be backwards-compatible, so I wouldn't expect any problems. If you have any, then this is a bug that you are welcome to report here.
